/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kursus.tabel;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import kursus.tabel.db.UserService;

/**
 *
 * @author linuxluv
 */
public class MainFrameWithPage extends javax.swing.JFrame {

    private DefaultTableModel modelTbl;
    int nomorHalaman = 1;
    int jumlahBarisPerhalaman = 20;
    int totalHalaman = 1;
    int totalData = 0;
    UserService userService;

    /**
     * Creates new form MainFrame
     */
    public MainFrameWithPage() {
        initComponents();

        jcbJmlBaris.addItem("20");
        jcbJmlBaris.addItem("30");
        jcbJmlBaris.addItem("40");
        jcbJmlBaris.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                initPagination();
            }
        });
        userService = new UserService();
        /* set tabel model, atur header dan jumlah kolom tabel */
        modelTbl = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID User", "Username"
                }
        );
        jTable1.setModel(modelTbl);

        initPagination();

        /* event dieksekusi ketika terjadi perubahan teks di dalam textField */
        jtfCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                initPagination();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                initPagination();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                System.out.println("change " + jtfCari.getText());
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /* inisialisasi awal pagination */
    public void initPagination() {
        System.out.println("test......");
        
        /* testing number format */
        NumberFormat numFormatIndnesia = NumberFormat.getInstance(Locale.ITALY);
        System.out.println("test ----> "+numFormatIndnesia.format(1000000.123));
        
        DecimalFormat currencyFormatIndnesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        currencyFormatIndnesia.setDecimalFormatSymbols(formatRp);

        System.out.println("test ----> "+currencyFormatIndnesia.format(1000000.123));
        //-------------------------------

        totalData = userService.count(jtfCari.getText());
        jumlahBarisPerhalaman=Integer.valueOf(jcbJmlBaris.getSelectedItem().toString());
        Double totalHalamanD = Math.ceil(Double.parseDouble(String.valueOf(totalData))
                / Double.parseDouble(String.valueOf(jumlahBarisPerhalaman)));
        totalHalaman = totalHalamanD.intValue();

        if (nomorHalaman == 1) {
            jbFirst.setEnabled(false);
            jbPrev.setEnabled(false);
        } else {
            jbFirst.setEnabled(true);
            jbPrev.setEnabled(true);
        }

        if (nomorHalaman == totalHalaman) {
            jbLast.setEnabled(false);
            jbNext.setEnabled(false);
        } else {
            jbLast.setEnabled(true);
            jbNext.setEnabled(true);
        }

        if (nomorHalaman > totalHalaman) {
            nomorHalaman = 1;
        }

//        userService.getAllDataUser(modelTbl, nomorHalaman, jumlahBarisPerhalaman);
        userService.searchDataUser(jtfCari.getText(), modelTbl, nomorHalaman, jumlahBarisPerhalaman);
        jlStatusHlm.setText("Halaman " + nomorHalaman + " dari " + totalHalaman);
        jlTotalData.setText(("Total data " + totalData));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCari = new javax.swing.JTextField();
        jbLast = new javax.swing.JButton();
        jbNext = new javax.swing.JButton();
        jbPrev = new javax.swing.JButton();
        jcbJmlBaris = new javax.swing.JComboBox<>();
        jbFirst = new javax.swing.JButton();
        jlStatusHlm = new javax.swing.JLabel();
        jlTotalData = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("cari");

        jtfCari.setPreferredSize(new java.awt.Dimension(14, 30));

        jbLast.setText(">>");
        jbLast.setPreferredSize(new java.awt.Dimension(55, 30));
        jbLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLastActionPerformed(evt);
            }
        });

        jbNext.setText(">");
        jbNext.setPreferredSize(new java.awt.Dimension(45, 30));
        jbNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextActionPerformed(evt);
            }
        });

        jbPrev.setText("<");
        jbPrev.setPreferredSize(new java.awt.Dimension(45, 30));
        jbPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrevActionPerformed(evt);
            }
        });

        jcbJmlBaris.setPreferredSize(new java.awt.Dimension(73, 30));

        jbFirst.setText("<<");
        jbFirst.setPreferredSize(new java.awt.Dimension(55, 30));
        jbFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFirstActionPerformed(evt);
            }
        });

        jlStatusHlm.setText("[status hlm]");

        jlTotalData.setText("[total data]");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlTotalData)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlStatusHlm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCari, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbJmlBaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNext, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jbLast, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addComponent(jbPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbJmlBaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotalData)
                    .addComponent(jlStatusHlm)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFirstActionPerformed
        // TODO add your handling code here:
        nomorHalaman = 1;
        initPagination();
    }//GEN-LAST:event_jbFirstActionPerformed

    private void jbPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrevActionPerformed
        // TODO add your handling code here:
        if (nomorHalaman > 1) {
            nomorHalaman--;
            initPagination();
        }
    }//GEN-LAST:event_jbPrevActionPerformed

    private void jbNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextActionPerformed
        // TODO add your handling code here:
        if (nomorHalaman < totalHalaman) {
            nomorHalaman++;
            initPagination();;
        }
    }//GEN-LAST:event_jbNextActionPerformed

    private void jbLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLastActionPerformed
        // TODO add your handling code here:
        nomorHalaman = totalHalaman;
        initPagination();
    }//GEN-LAST:event_jbLastActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TestJDialog tj = new TestJDialog(this, true, this);
        tj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbFirst;
    private javax.swing.JButton jbLast;
    private javax.swing.JButton jbNext;
    private javax.swing.JButton jbPrev;
    private javax.swing.JComboBox<String> jcbJmlBaris;
    private javax.swing.JLabel jlStatusHlm;
    private javax.swing.JLabel jlTotalData;
    private javax.swing.JTextField jtfCari;
    // End of variables declaration//GEN-END:variables
}
